--Creating a new table and inserting the values using joins. Using the two keys given.
CREATE TABLE input_data_main(
  masked_acct TEXT NOT NULL,
  key_1 TEXT NOT NULL,
  key_2 TEXT NOT NULL,
  Vintage INT,
  ChargeOffMonthKey INT,
  ChargeOffMOB INT,
  Loss_Date_150 TEXT,
  BalanceAtDefault REAL,
  JointIndicator INT,
  LCPIndicator INT,
  FICOScore TEXT,
  StateApplicant TEXT,
  FICOScorePctAvgFICOLast30DaysBookedLoans TEXT,
  ApplicationWeekday INT,
  NewUsedIndicator INT,
  VehicleManufacturerRebate REAL,
  VehicleAge INT,
  VehicleMileage INT,
  VehicleValueBlackBook INT,
  TradeInIndicator INT,
  TradeInAmt TEXT,
  VehicleMakeNADA TEXT,
  VehicleModelNADA TEXT,
  JDPowerUsedVehicleIndex REAL,
  MoodysNumUnemployed REAL,
  MoodysUsedVehicleIndex REAL,
  MoodysNumEmployed REAL,
  MoodysGDPReal REAL,
  MoodysGasoline REAL,
  MoodysNumLaborForce REAL,
  MoodysUnemploymentRate REAL,
  TradeInPctBBVehicleValue TEXT,
  TradeInPctLine3 TEXT,
  TradeInPctLine4 TEXT,
  TradeInPctLine5 TEXT,
  FinancedAmt REAL,
  LoanAmtLine3 REAL,
  LoanAmtLine4 REAL,
  LTVLine3 REAL,
  LTVLine4 REAL,
  LTVLine5 REAL,
  LTVLine3ExclRebate REAL,
  LTVLine4ExclRebate REAL,
  LTVLine5ExclRebate REAL,
  CashDownPmt REAL,
  CashDownPmtPctBBVehicleValue REAL,
  CashDownPmtPctLine3 REAL,
  CashDownPmtPctLine4 REAL,
  CashDownPmtPctLine5 REAL,
  PaymentAmt REAL,
  PaymentToFinancedAmtRatio REAL,
  PTILine5 REAL,
  BackendGapAmt REAL,
  BackendWarrantyAmt REAL,
  BackendTotalAmt REAL,
  BackendType TEXT,
  BackendTotalPctBBVehicleValue REAL,
  BackendTotalPctBBVehicleValueGTE13PctIndicator INT,
  BackendTotalPctLine3 REAL,
  BackendTotalPctLine4 REAL,
  BackendTotalPctLine5 REAL,
  TotalDownPmt REAL,
  TotalDownPmtPctBBVehicleValue REAL,
  TotalDownPmtPctLine3 REAL,
  TotalDownPmtPctLine4 REAL,
  TotalDownPmtPctLine5 REAL,
  DealerReserve REAL,
  ContractRate REAL,
  BuyRate REAL,
  DealerFeeNet REAL,
  NumJobsApplicant INT,
  EmploymentMonthsSinceHiredCurrentEmployerApplicant INT,
  EmploymentJobTypeApplicant TEXT,
  CreditBureauNumTrades INT,
  CreditBureauNumTradesCurrent INT,
  CreditBureauNumCollections INT,
  CreditBureauRevolvingCreditLinePctUsed TEXT,
  CreditBureauPctTradesDelq TEXT,
  NumExceptionALL INT,
  NumExceptionLTV INT,
  NumExceptionPTI INT,
  NumExceptionDTI INT,
  NumExceptionPctAvgNumExceptionLast30DaysBookedLoans REAL,
  NumPriorCrescentApplications INT,
  NumPriorCrescentApplicationsLast30Days INT,
  NumPriorCrescentApplicationsLast60Days INT,
  NumPriorCrescentApplicationsLast90Days INT,
  NumPriorCrescentApplicationsLast180Days INT,
  JDPUVIDiffCOFromOrig REAL,
  MoodysUVIDiffCOFromOrig REAL,
  PRIMARY KEY(masked_acct) 
)
INSERT INTO input_data_main
SELECT --DISTINCT 
masked_acct,
ID_1.key_1,
ID_4.key_2,
Vintage,
ChargeOffMonthKey,
ChargeOffMOB,
Loss_Date_150,
BalanceAtDefault,
JointIndicator,
LCPIndicator,
FICOScore,
StateApplicant,
FICOScorePctAvgFICOLast30DaysBookedLoans,
ApplicationWeekday,
NewUsedIndicator,
VehicleManufacturerRebate,
VehicleAge,
VehicleMileage,
VehicleValueBlackBook,
TradeInIndicator,
TradeInAmt,
VehicleMakeNADA,
VehicleModelNADA,
JDPowerUsedVehicleIndex,
MoodysNumUnemployed,
MoodysUsedVehicleIndex,
MoodysNumEmployed,
MoodysGDPReal,
MoodysGasoline,
MoodysNumLaborForce,
MoodysUnemploymentRate,
TradeInPctBBVehicleValue,
TradeInPctLine3,
TradeInPctLine4,
TradeInPctLine5,
FinancedAmt,
LoanAmtLine3,
LoanAmtLine4,
LTVLine3,
LTVLine4,
LTVLine5,
LTVLine3ExclRebate,
LTVLine4ExclRebate,
LTVLine5ExclRebate,
CashDownPmt,
CashDownPmtPctBBVehicleValue,
CashDownPmtPctLine3,
CashDownPmtPctLine4,
CashDownPmtPctLine5,
PaymentAmt,
PaymentToFinancedAmtRatio,
PTILine5,
BackendGapAmt,
BackendWarrantyAmt,
BackendTotalAmt,
BackendType,
BackendTotalPctBBVehicleValue,
BackendTotalPctBBVehicleValueGTE13PctIndicator,
BackendTotalPctLine3,
BackendTotalPctLine4,
BackendTotalPctLine5,
TotalDownPmt,
TotalDownPmtPctBBVehicleValue,
TotalDownPmtPctLine3,
TotalDownPmtPctLine4,
TotalDownPmtPctLine5,
DealerReserve,
ContractRate,
BuyRate,
DealerFeeNet,
NumJobsApplicant,
EmploymentMonthsSinceHiredCurrentEmployerApplicant,
EmploymentJobTypeApplicant,
CreditBureauNumTrades,
CreditBureauNumTradesCurrent,
CreditBureauNumCollections,
CreditBureauRevolvingCreditLinePctUsed,
CreditBureauPctTradesDelq,
NumExceptionALL,
NumExceptionLTV,
NumExceptionPTI,
NumExceptionDTI,
NumExceptionPctAvgNumExceptionLast30DaysBookedLoans,
NumPriorCrescentApplications,
NumPriorCrescentApplicationsLast30Days,
NumPriorCrescentApplicationsLast60Days,
NumPriorCrescentApplicationsLast90Days,
NumPriorCrescentApplicationsLast180Days,
JDPUVIDiffCOFromOrig,
MoodysUVIDiffCOFromOrig

FROM input_data_1 AS ID_1 LEFT JOIN input_data_4 AS ID_4 ON ID_1.key_1 = ID_4.key_1 LEFT JOIN input_data_7 AS ID_7 ON ID_4.key_2 = ID_7.key_2

UNION ALL
SELECT --DISTINCT 
masked_acct,
ID_2.key_1,
ID_5.key_2,
Vintage,
ChargeOffMonthKey,
ChargeOffMOB,
Loss_Date_150,
BalanceAtDefault,
JointIndicator,
LCPIndicator,
FICOScore,
StateApplicant,
FICOScorePctAvgFICOLast30DaysBookedLoans,
ApplicationWeekday,
NewUsedIndicator,
VehicleManufacturerRebate,
VehicleAge,
VehicleMileage,
VehicleValueBlackBook,
TradeInIndicator,
TradeInAmt,
VehicleMakeNADA,
VehicleModelNADA,
JDPowerUsedVehicleIndex,
MoodysNumUnemployed,
MoodysUsedVehicleIndex,
MoodysNumEmployed,
MoodysGDPReal,
MoodysGasoline,
MoodysNumLaborForce,
MoodysUnemploymentRate,
TradeInPctBBVehicleValue,
TradeInPctLine3,
TradeInPctLine4,
TradeInPctLine5,
FinancedAmt,
LoanAmtLine3,
LoanAmtLine4,
LTVLine3,
LTVLine4,
LTVLine5,
LTVLine3ExclRebate,
LTVLine4ExclRebate,
LTVLine5ExclRebate,
CashDownPmt,
CashDownPmtPctBBVehicleValue,
CashDownPmtPctLine3,
CashDownPmtPctLine4,
CashDownPmtPctLine5,
PaymentAmt,
PaymentToFinancedAmtRatio,
PTILine5,
BackendGapAmt,
BackendWarrantyAmt,
BackendTotalAmt,
BackendType,
BackendTotalPctBBVehicleValue,
BackendTotalPctBBVehicleValueGTE13PctIndicator,
BackendTotalPctLine3,
BackendTotalPctLine4,
BackendTotalPctLine5,
TotalDownPmt,
TotalDownPmtPctBBVehicleValue,
TotalDownPmtPctLine3,
TotalDownPmtPctLine4,
TotalDownPmtPctLine5,
DealerReserve,
ContractRate,
BuyRate,
DealerFeeNet,
NumJobsApplicant,
EmploymentMonthsSinceHiredCurrentEmployerApplicant,
EmploymentJobTypeApplicant,
CreditBureauNumTrades,
CreditBureauNumTradesCurrent,
CreditBureauNumCollections,
CreditBureauRevolvingCreditLinePctUsed,
CreditBureauPctTradesDelq,
NumExceptionALL,
NumExceptionLTV,
NumExceptionPTI,
NumExceptionDTI,
NumExceptionPctAvgNumExceptionLast30DaysBookedLoans,
NumPriorCrescentApplications,
NumPriorCrescentApplicationsLast30Days,
NumPriorCrescentApplicationsLast60Days,
NumPriorCrescentApplicationsLast90Days,
NumPriorCrescentApplicationsLast180Days,
JDPUVIDiffCOFromOrig,
MoodysUVIDiffCOFromOrig

FROM input_data_2 AS ID_2 LEFT JOIN input_data_5 AS ID_5 ON ID_2.key_1 = ID_5.key_1 
LEFT JOIN input_data_8 AS ID_8 ON ID_5.key_2 = ID_8.key_2

UNION ALL
SELECT --DISTINCT  
masked_acct,
ID_3.key_1,
ID_6.key_2,
Vintage,
ChargeOffMonthKey,
ChargeOffMOB,
Loss_Date_150,
BalanceAtDefault,
JointIndicator,
LCPIndicator,
FICOScore,
StateApplicant,
FICOScorePctAvgFICOLast30DaysBookedLoans,
ApplicationWeekday,
NewUsedIndicator,
VehicleManufacturerRebate,
VehicleAge,
VehicleMileage,
VehicleValueBlackBook,
TradeInIndicator,
TradeInAmt,
VehicleMakeNADA,
VehicleModelNADA,
JDPowerUsedVehicleIndex,
MoodysNumUnemployed,
MoodysUsedVehicleIndex,
MoodysNumEmployed,
MoodysGDPReal,
MoodysGasoline,
MoodysNumLaborForce,
MoodysUnemploymentRate,
TradeInPctBBVehicleValue,
TradeInPctLine3,
TradeInPctLine4,
TradeInPctLine5,
FinancedAmt,
LoanAmtLine3,
LoanAmtLine4,
LTVLine3,
LTVLine4,
LTVLine5,
LTVLine3ExclRebate,
LTVLine4ExclRebate,
LTVLine5ExclRebate,
CashDownPmt,
CashDownPmtPctBBVehicleValue,
CashDownPmtPctLine3,
CashDownPmtPctLine4,
CashDownPmtPctLine5,
PaymentAmt,
PaymentToFinancedAmtRatio,
PTILine5,
BackendGapAmt,
BackendWarrantyAmt,
BackendTotalAmt,
BackendType,
BackendTotalPctBBVehicleValue,
BackendTotalPctBBVehicleValueGTE13PctIndicator,
BackendTotalPctLine3,
BackendTotalPctLine4,
BackendTotalPctLine5,
TotalDownPmt,
TotalDownPmtPctBBVehicleValue,
TotalDownPmtPctLine3,
TotalDownPmtPctLine4,
TotalDownPmtPctLine5,
DealerReserve,
ContractRate,
BuyRate,
DealerFeeNet,
NumJobsApplicant,
EmploymentMonthsSinceHiredCurrentEmployerApplicant,
EmploymentJobTypeApplicant,
CreditBureauNumTrades,
CreditBureauNumTradesCurrent,
CreditBureauNumCollections,
CreditBureauRevolvingCreditLinePctUsed,
CreditBureauPctTradesDelq,
NumExceptionALL,
NumExceptionLTV,
NumExceptionPTI,
NumExceptionDTI,
NumExceptionPctAvgNumExceptionLast30DaysBookedLoans,
NumPriorCrescentApplications,
NumPriorCrescentApplicationsLast30Days,
NumPriorCrescentApplicationsLast60Days,
NumPriorCrescentApplicationsLast90Days,
NumPriorCrescentApplicationsLast180Days,
JDPUVIDiffCOFromOrig,
MoodysUVIDiffCOFromOrig

FROM input_data_3 AS ID_3 LEFT JOIN input_data_6 AS ID_6 ON ID_3.key_1 = ID_6.key_1 
LEFT JOIN input_data_9 AS ID_9 ON ID_6.key_2 = ID_9.key_2
-- Creating another table with masked account and RecoveryPctBalanceAtDefaultRatioMACO12 using dense rank and partition.
CREATE TABLE "True_target" (
	"masked_acct"	TEXT,
	"RecoveryPctBalanceAtDefaultRatioMACO12"	REAL
)
INSERT INTO True_target
SELECT masked_acct, (sum(RecoveryPctBalanceAtDefaultRatioMACO12)/2) FROM 
(SELECT masked_acct, min(score_ind),RecoveryPctBalanceAtDefaultRatioMACO12  FROM target GROUP BY masked_acct
UNION  
Select masked_acct,score_ind,RecoveryPctBalanceAtDefaultRatioMACO12 from 
(SELECT *,dense_rank() over ( PARTITION by masked_acct order by score_ind desc ) as num FROM target ) a 
where a.num = 2 ) GROUP BY masked_acct
-- Creating a final table using both the tables, resulting in the combined data table with target values mentioned.
CREATE TABLE input_data_true(
  masked_acct TEXT NOT NULL,
  RecoveryPctBalanceAtDefaultRatioMACO12 REAL,
  Vintage INT,
  ChargeOffMonthKey INT,
  ChargeOffMOB INT,
  Loss_Date_150 TEXT,
  BalanceAtDefault REAL,
  JointIndicator INT,
  LCPIndicator INT,
  FICOScore TEXT,
  StateApplicant TEXT,
  FICOScorePctAvgFICOLast30DaysBookedLoans TEXT,
  ApplicationWeekday INT,
  NewUsedIndicator INT,
  VehicleManufacturerRebate REAL,
  VehicleAge INT,
  VehicleMileage INT,
  VehicleValueBlackBook INT,
  TradeInIndicator INT,
  TradeInAmt TEXT,
  VehicleMakeNADA TEXT,
  VehicleModelNADA TEXT,
  JDPowerUsedVehicleIndex REAL,
  MoodysNumUnemployed REAL,
  MoodysUsedVehicleIndex REAL,
  MoodysNumEmployed REAL,
  MoodysGDPReal REAL,
  MoodysGasoline REAL,
  MoodysNumLaborForce REAL,
  MoodysUnemploymentRate REAL,
  TradeInPctBBVehicleValue TEXT,
  TradeInPctLine3 TEXT,
  TradeInPctLine4 TEXT,
  TradeInPctLine5 TEXT,
  FinancedAmt REAL,
  LoanAmtLine3 REAL,
  LoanAmtLine4 REAL,
  LTVLine3 REAL,
  LTVLine4 REAL,
  LTVLine5 REAL,
  LTVLine3ExclRebate REAL,
  LTVLine4ExclRebate REAL,
  LTVLine5ExclRebate REAL,
  CashDownPmt REAL,
  CashDownPmtPctBBVehicleValue REAL,
  CashDownPmtPctLine3 REAL,
  CashDownPmtPctLine4 REAL,
  CashDownPmtPctLine5 REAL,
  PaymentAmt REAL,
  PaymentToFinancedAmtRatio REAL,
  PTILine5 REAL,
  BackendGapAmt REAL,
  BackendWarrantyAmt REAL,
  BackendTotalAmt REAL,
  BackendType TEXT,
  BackendTotalPctBBVehicleValue REAL,
  BackendTotalPctBBVehicleValueGTE13PctIndicator INT,
  BackendTotalPctLine3 REAL,
  BackendTotalPctLine4 REAL,
  BackendTotalPctLine5 REAL,
  TotalDownPmt REAL,
  TotalDownPmtPctBBVehicleValue REAL,
  TotalDownPmtPctLine3 REAL,
  TotalDownPmtPctLine4 REAL,
  TotalDownPmtPctLine5 REAL,
  DealerReserve REAL,
  ContractRate REAL,
  BuyRate REAL,
  DealerFeeNet REAL,
  NumJobsApplicant INT,
  EmploymentMonthsSinceHiredCurrentEmployerApplicant INT,
  EmploymentJobTypeApplicant TEXT,
  CreditBureauNumTrades INT,
  CreditBureauNumTradesCurrent INT,
  CreditBureauNumCollections INT,
  CreditBureauRevolvingCreditLinePctUsed TEXT,
  CreditBureauPctTradesDelq TEXT,
  NumExceptionALL INT,
  NumExceptionLTV INT,
  NumExceptionPTI INT,
  NumExceptionDTI INT,
  NumExceptionPctAvgNumExceptionLast30DaysBookedLoans REAL,
  NumPriorCrescentApplications INT,
  NumPriorCrescentApplicationsLast30Days INT,
  NumPriorCrescentApplicationsLast60Days INT,
  NumPriorCrescentApplicationsLast90Days INT,
  NumPriorCrescentApplicationsLast180Days INT,
  JDPUVIDiffCOFromOrig REAL,
  MoodysUVIDiffCOFromOrig REAL
)

INSERT INTO input_data_true

SELECT --DISTINCT 
T.masked_acct,
RecoveryPctBalanceAtDefaultRatioMACO12,
Vintage,
ChargeOffMonthKey,
ChargeOffMOB,
Loss_Date_150,
BalanceAtDefault,
JointIndicator,
LCPIndicator,
FICOScore,
StateApplicant,
FICOScorePctAvgFICOLast30DaysBookedLoans,
ApplicationWeekday,
NewUsedIndicator,
VehicleManufacturerRebate,
VehicleAge,
VehicleMileage,
VehicleValueBlackBook,
TradeInIndicator,
TradeInAmt,
VehicleMakeNADA,
VehicleModelNADA,
JDPowerUsedVehicleIndex,
MoodysNumUnemployed,
MoodysUsedVehicleIndex,
MoodysNumEmployed,
MoodysGDPReal,
MoodysGasoline,
MoodysNumLaborForce,
MoodysUnemploymentRate,
TradeInPctBBVehicleValue,
TradeInPctLine3,
TradeInPctLine4,
TradeInPctLine5,
FinancedAmt,
LoanAmtLine3,
LoanAmtLine4,
LTVLine3,
LTVLine4,
LTVLine5,
LTVLine3ExclRebate,
LTVLine4ExclRebate,
LTVLine5ExclRebate,
CashDownPmt,
CashDownPmtPctBBVehicleValue,
CashDownPmtPctLine3,
CashDownPmtPctLine4,
CashDownPmtPctLine5,
PaymentAmt,
PaymentToFinancedAmtRatio,
PTILine5,
BackendGapAmt,
BackendWarrantyAmt,
BackendTotalAmt,
BackendType,
BackendTotalPctBBVehicleValue,
BackendTotalPctBBVehicleValueGTE13PctIndicator,
BackendTotalPctLine3,
BackendTotalPctLine4,
BackendTotalPctLine5,
TotalDownPmt,
TotalDownPmtPctBBVehicleValue,
TotalDownPmtPctLine3,
TotalDownPmtPctLine4,
TotalDownPmtPctLine5,
DealerReserve,
ContractRate,
BuyRate,
DealerFeeNet,
NumJobsApplicant,
EmploymentMonthsSinceHiredCurrentEmployerApplicant,
EmploymentJobTypeApplicant,
CreditBureauNumTrades,
CreditBureauNumTradesCurrent,
CreditBureauNumCollections,
CreditBureauRevolvingCreditLinePctUsed,
CreditBureauPctTradesDelq,
NumExceptionALL,
NumExceptionLTV,
NumExceptionPTI,
NumExceptionDTI,
NumExceptionPctAvgNumExceptionLast30DaysBookedLoans,
NumPriorCrescentApplications,
NumPriorCrescentApplicationsLast30Days,
NumPriorCrescentApplicationsLast60Days,
NumPriorCrescentApplicationsLast90Days,
NumPriorCrescentApplicationsLast180Days,
JDPUVIDiffCOFromOrig,
MoodysUVIDiffCOFromOrig

FROM input_data_main AS ID_M LEFT JOIN True_target AS T ON ID_M.masked_acct = T.masked_acct
